### ISSUE TITLE
`Segmentation fault: 11` on input image.

### ISSUE THREAD

**Issue by MrJoy** [google/guetzli#102]
The image seems valid, and is certainly readable and producing correct results for an array of tools / viewers I've tried it with.  Instead of either being processed properly or producing an error about the file not being well-formed, `guetzli` segfaults when invoked against this image.  I have not used any flags -- just `guetzli input.jpg output.jpg`.  This is after installing `guetzli` for the first time via `brew install guetzli`, on a system running macOS 10.12.3.

Any other information I can provide?

![employer-avatar](https://cloud.githubusercontent.com/assets/113625/24123803/43a578c0-0d7e-11e7-8cc7-c94d781a607a.jpg)

**Comment by MrJoy** [comment]
(Sorry, to be clear: the icon there is the offending image...)

**Comment by robryk** [comment]
This is most likely #38. While it's fixed, the Homebrew build recipe(?) hasn't been updated yet. I will try to cause that to happen tomorrow (#95).

In the meantime, following the instructions on how to compile Guetzli will work the problem around.

All that said, Guetzli will currently not do much with such small images, because they are too small for Butteraugli (our image comparator) to give very meaningful results.

**Comment by MrJoy** [comment]
Thanks!  As for expectations:  I'm just looking into the possibility of applying this in an automated way as part of an asset pipeline -- I'm not really expecting _useful_ results on tiny files.
