### ISSUE TITLE
I want to use guetzli in the android app  

### ISSUE THREAD

**Issue by cwh-github** [google/guetzli#112]
how can I compile guetzli code to ".so" file, 
and i can use the ".so" file in the android app

help~

**Comment by ADDICTABLE99** [comment]
What is this app for

**Comment by cwh-github** [comment]
just study

**Comment by ADDICTABLE99** [comment]
Cool so I just go to google play store

**Comment by robryk** [comment]
In order to use Guetzli in an Android app, you not only need to compile it to an `.so` file, but also to compile it for the ARM CPU. It's easy to compile Guetzli to `.so` file for Intel CPU using Bazel: `bazel build -c opt :guetzli_lib`. Unfortunately Bazel's support for ARM is very experimental.

If you want to use Guetzli on Android, what I'd suggest is to try to compile the Guetzli *binary* for ARM, using the Makefile with an appropriate C++ compiler and linker specified manually:

```
make CXX=your-c++-compiler-for-arm LD=your-linked-for-arm
```

and use the support for starting a new process on Android.

All that said, please make sure that you'll have enough memory for your usecase.

**Comment by cwh-github** [comment]
Thank you for your advice.
