### ISSUE TITLE
Ubuntu 16.04 compilation error due to gflags was not found in the pkg-config search path.

### ISSUE THREAD

**Issue by JulianSSS** [google/guetzli#74]
After installing the needed packages as described in the README.MD using apt-get in Ubuntu 16.04 there's this error after running make:
`==== Building guetzli (release) ====
Linking guetzli
Package gflags was not found in the pkg-config search path.
Perhaps you should add the directory containing 'gflags.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gflags' found`
The `gflags.pc` file simply doesn't exist on the whole system.

**Comment by robryk** [comment]
It seems that that Ubuntu version indeed has a [libgflags-dev](http://packages.ubuntu.com/de/xenial/amd64/libgflags-dev/filelist) package without the `.pc` file. There's even an [issue](https://bugs.launchpad.net/ubuntu/+source/gflags/+bug/1469483) filed about that, but it has been fixed too late for 16.04. I will fix this somehow on Monday. As a workaround for the meantime, please use the version from commit 95ba42158eb46153944d5abc3bcb62f40e384186:
 - if you're using git to clone Guetzli, run `git checkout 95ba421`
 - otherwise, download the [source from that commit](https://github.com/google/guetzli/archive/95ba42158eb46153944d5abc3bcb62f40e384186.zip)

**Comment by robryk** [comment]
#97 removes the dependency on gflags. Please update to the current version, try again, and reopen if problems persist. Sorry for the trouble.

**Comment by JulianSSS** [comment]
Thanks once more here - it works directly!
